name: Build Mac App
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with: {python-version: '3.12'}
      - name: Install dependencies
        run: pip install pyinstaller ultralytics opencv-python-headless onnxruntime
      - name: Build App
        run: pyinstaller --onefile Test_Pipeline.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mac_App
          path: dist/Test_Pipeline
